on: [push]

jobs:
  playwright-automation-run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install npm dependencies
        run: npm ci

      - name: Install npm dependencies
        run: npx playwright install
        
      - name: Run NG server
        run: npm run start & sleep 10

      - name: Run tests
        run: npm run test

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ./playwright-report
          path: playwright-report/
          retention-days: 30
